import Head from "next/head";

import { AnimateSharedLayout, motion, AnimatePresence } from "framer-motion";
import { useEffect, useState } from "react";
import Loading from "./components/Utils/loading";
import Header from "./components/Header/Header";
import HomePage from "./components/Mainpage/HomePage";
import Footer from "./components/Footer/Footer";
import Projects from "./components/Projects/Projects";
import Driver from "./components/Projects/Driver";
import { Stack, useBreakpointValue } from "@chakra-ui/react";
export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const timeout = setTimeout(() => {
      setLoading(false);
    }, 4000);
  }, []);
  return (
    <div>
      <Head>
        <title>Ankit Gautam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimateSharedLayout>
        <AnimatePresence exitBeforeEnter>
          {loading && (
            <motion.h2
              key={"theThanks"}
              className="w-full h-screen flex items-center justify-center"
              transition={{
                ease: "backInOut",
              }}
              exit={{ opacity: 0, y: 200 }}
            >
              <Loading />
            </motion.h2>
          )}
          {!loading && (
            <motion.div key={"theThanks"} exit={{ y: -100 }}>
              <div
                className="overflow-x-hidden"
                style={{ fontFamily: "Montserrat_Medium" }}
              >
                <Header />
                <div
                  className=" w-full h-[96vh]  flex max-h-[850px] min-h-[600px] items-center justify-center"
                  style={{
                    marginTop: "25px",
                  }}
                  id="Home"
                >
                  <HomePage />
                </div>
                <Stack
                  id="Projects"
                  className=" w-full   h-[1200px] md:h-[800px] lg:h-[650px] lg:pt-0 md:pl-0 flex  min-h-[600px] items-center justify-center"
                >
                  <Projects />
                </Stack>
                <Stack
                  id="Projects"
                  className=" w-full   h-[1200px] md:h-[800px] lg:h-[650px] lg:pt-0 md:pl-0 flex  min-h-[600px] items-center justify-center"
                >
                  <Driver />
                </Stack>
                <div
                  className="h-screen  w-full flex items-center min-h-[1100px] mob:min-h-[1500px]  md:min-h-[350px] justify-center"
                  style={{
                    fontFamily: "Montserrat_Medium",
                    paddingTop: "25px",
                  }}
                  id="Edu"
                ></div>
                <div
                  className="h-screen w-full flex items-center justify-center"
                  style={{
                    fontFamily: "Montserrat_Medium",
                    paddingTop: "25px",
                  }}
                  id="About_me"
                >
                  About me
                </div>
                <Footer />
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </AnimateSharedLayout>
    </div>
  );
}
